//---------Comparison----------

console.log( 4 < 9); // true
console.log( 4 > 9); // false
console.log( 4 <= 9); // true
console.log( 4 >= 9); // false
console.log( 4 == 4); // true
console.log( 4 != 4); // false
console.log( 4 == 9); // false
console.log( 4 != 9); // true
console.log( 4 === 9); // false
console.log( 4 !== 9); // true
console.log( 4 == "4"); // true
console.log( 4 === "4"); // false
console.log( 4 != "4"); // false
console.log( 4 !== "4"); // true
console.log( 4 == true); // true
console.log( 4 === true); // false
console.log( 4 != true); // false
console.log( 4 !== true); // true
console.log( 4 == false); // false
console.log( 4 === false); // false
console.log( 4 != false); // true
console.log( 4 !== false); // true
console.log( 4 == null); // false
console.log( 4 === null); // false
console.log( 4 != null); // true
console.log( 4 !== null); // true
console.log( 4 == undefined); // false
console.log( 4 === undefined); // false
console.log( 4 != undefined); // true
console.log( 4 !== undefined); // true
console.log( 4 == NaN); // false
console.log( 4 === NaN); // false
console.log( 4 != NaN); // true
console.log( 4 !== NaN); // true
console.log( 4 == Infinity); // false
console.log( 4 === Infinity); // false
console.log( 4 != Infinity); // true
console.log( 4 !== Infinity); // true
console.log( 4 == -Infinity); // false
console.log( 4 === -Infinity); // false
console.log( 4 != -Infinity); // true
console.log( 4 !== -Infinity); // true
console.log( 4 == 0); // false
console.log( 4 === 0); // false
console.log( 4 != 0); // true
console.log( 4 !== 0); // true
console.log( 4 == ""); // false
console.log( 4 === ""); // false
console.log( 4 != ""); // true
console.log( 4 !== ""); // true
console.log( 4 == " "); // false
console.log( 4 === " "); // false
console.log( 4 != " "); // true
console.log( 4 !== " "); // true
console.log( 4 == "0"); // false
console.log( 4 === "0"); // false
console.log( 4 != "0"); // true
console.log( 4 !== "0"); // true
console.log( 4 == "1"); // false
console.log( 4 === "1"); // false
console.log( 4 != "1"); // true
console.log( 4 !== "1"); // true
console.log( 4 == "2"); // false
console.log( 4 === "2"); // false
console.log( 4 != "2"); // true
console.log( 4 !== "2"); // true
console.log( 4 == "3"); // false
console.log( 4 === "3"); // false
console.log( 4 != "3"); // true
console.log( 4 !== "3"); // true
console.log( 4 == "4"); // true
console.log( 4 === "4"); // false
console.log( 4 != "4"); // false
console.log( 4 !== "4"); // true